version: '3.8'
services:
  flaskapp:
    container_name: flaskapp
    image: flask:v1
    networks:
      - mongo-single-network
    expose:
      - 5000
    ports:
      - "4000:5000"
    restart: always
  mongodb:
    container_name: mongo
    image: mongo:7.0.3
    networks:
      - mongo-single-network
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0
    networks:
      - mongo-single-network
    ports:
      - '8081:8081'

volumes:
  dbdata:

networks:
  mongo-single-network:
    driver: bridge
